# Generated by Django 5.2.10 on 2026-02-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0002_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='video_url',
            new_name='video_embed_url',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_body',
        ),
        migrations.AddField(
            model_name='lesson',
            name='raw_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
