# Generated by Django 6.0.2 on 2026-02-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0003_rename_video_url_lesson_video_embed_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mother_phone_number',
        ),
    ]
