# Generated by Django 6.0.2 on 2026-02-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0003_rename_video_url_lesson_video_embed_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('user', 'quiz', 'attempt_number')},
        ),
    ]
