# Generated by Django 6.0.2 on 2026-03-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0004_alter_quizresult_unique_together_quiz_max_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, help_text='Downloadable file (e.g. .docx, .pdf) uploaded by instructor.', null=True, upload_to='assignments/files/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_code_display',
            field=models.CharField(blank=True, default='', help_text='Course code (e.g. CS389/CS486).', max_length=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_name_display',
            field=models.CharField(blank=True, default='', help_text='Course name shown on assignment page (e.g. Image Processing).', max_length=200),
        ),
        migrations.AddField(
            model_name='assignment',
            name='learning_objectives',
            field=models.TextField(blank=True, default='', help_text='Bullet points describing what the student will learn.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='opened_at',
            field=models.DateTimeField(blank=True, help_text='When the assignment becomes available.', null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='grading_status',
            field=models.CharField(choices=[('not_graded', 'Not graded'), ('graded', 'Graded')], default='not_graded', max_length=20),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(help_text='Due date and time.'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
