# Generated by Django 6.0.2 on 2026-03-05 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0005_assignment_lms_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='True when the student has deleted the active submission.'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_comments',
            field=models.TextField(blank=True, default='', help_text='Instructor feedback or comments visible to the student.'),
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('submitted', 'Submitted'), ('edited', 'Edited'), ('deleted', 'Deleted')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/submissions/history/')),
                ('file_name', models.CharField(blank=True, default='', help_text='Original filename as uploaded by the student.', max_length=255)),
                ('answer_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_history', to='teach.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
